##===- examples/Fibonacci/Makefile -------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../..
TOOLNAME = WorkshopExample1MulAdd
EXAMPLE_TOOL = 1

# Link in JIT support
LINK_COMPONENTS := interpreter mcjit nativecodegen bitwriter

include $(LEVEL)/Makefile.common
